---
- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - git
      - autojump
      - thefuck
  
  - name: Remove packages
    apt: name={{item}}
    state: absent
    with_items:
      - neovim