---
- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      state: latest
      pkg:
      - git
      - autojump
      - thefuck
  
  - name: Remove packages
    apt:
      state: absent
      name: neovim